---
# tasks file for role-Common
- name: create users
  user: name="{{ item }}" shell=/bin/bash password="{{ vault_user_pass }}"
  with_items: "{{ common_users }}"

- name: create ssh directory for users
  file: path="/home/{{ item }}/.ssh" state=directory
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ common_users }}"

- name: add authorized keys for users
  authorized_key: user="{{ item[0] }}" key="{{ item[1] }}"
  with_nested:
    - "{{ common_authorized_users }}"
    - "{{ common_authorized_keys }}"

- name: add to wheel
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
  with_items: "{{ common_add_to_sudoers }}"

- name: Disable empty password login
  lineinfile:
    path: "{{ common_sshd_config }}"
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
    notify: 
    - restart sshd

- name: Disable root login
  lineinfile:
    path: "{{ common_sshd_config }}"
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    notify: 
    - restart sshd

- name: Enable epel
  yum:
    name: epel-release
    state: present

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"