---
# tasks file for role-Common
- name: Disable empty password login
  lineinfile:
    path: "{{ common_sshd_config }}"
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  notify: 
  - restart sshd

- name: Disable root login
  lineinfile:
    path: "{{ common_sshd_config }}"
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: 
  - restart sshd

- name: Enable epel
  yum:
    name: epel-release
    state: present

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"

- name: Drop new chrony configuration
  tempate:
    src: chrony.conf.j2
    dest: "/etc/chrony.conf"
  notify:
  - restart chrony